server:
  port: 8070
  servlet:
    context-path: /api

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/everkeep?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      # 初始化连接池大小
      initialSize: 5
      # 最小连接数
      minIdle: 5
      # 最大连接数
      maxActive: 40

  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 10
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 10
      # 连接超时时间（毫秒）
      timeout: 1000

# 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: /tmp/upload

# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 前缀 例如:Bearer
  token-prefix: Bearer
  timeout: 2592000
  is-read-cookie: false
  is-read-header: true

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  global-config:
    db-config:
      id-type: auto
      #数据库大写下划线转换
      capital-mode: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: false
    cache-enabled: false
    call-setters-on-nulls: true

# 日志配置
logging:
  level:
    # 将你的 Mapper 接口所在的包路径设置为 debug 级别
    org.xcyms.mapper: debug