version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: docker.m.daocloud.io/library/mysql:8.0
    container_name: everkeep-mysql
    restart: always
    environment:
      MYSQL_DATABASE: everkeep
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d

  # Redis 缓存
  redis:
    image: docker.m.daocloud.io/library/redis:alpine
    container_name: everkeep-redis
    restart: always
    ports:
      - "6379:6379"

  # 后端服务
  everkeep-server:
    build: ./EverKeep-server
    container_name: everkeep-server
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      - spring.datasource.druid.password=123456
    ports:
      - "8070:8070"
    # 图片保存目录  对应数据库  
    volumes:
      - ./uploads:/data/uploads

  # 前端服务
  everkeep-web:
    build: ./EverKeep-web
    container_name: everkeep-web
    restart: always
    depends_on:
      - everkeep-server
    ports:
      - "80:80"
  # 图片保存目录  对应数据库  
    volumes:
      - ./uploads:/data/uploads